databases:
  - name: payflow-postgres
    databaseName: payflow
    user: payflow
    plan: free

services:
  - type: web
    name: payflow-rtgs
    runtime: go
    plan: starter
    rootDir: rtgs-core
    buildCommand: go build -o rtgs-core ./cmd/main.go
    startCommand: ./rtgs-core
    envVars:
      - key: PORT
        value: 8082
      - key: DATABASE_URL
        fromDatabase:
          name: payflow-postgres
          property: connectionString

  - type: web
    name: payflow-exception-resolver
    runtime: python
    plan: starter
    rootDir: exception-resolver
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payflow-postgres
          property: connectionString

  - type: web
    name: payflow-dashboard
    runtime: static
    plan: starter
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist
