global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rtgs-core'
    static_configs:
      - targets: ['rtgs-core:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8081']
